### ISSUE TITLE
can't login in  SDK v3.1.0

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#10]
show that :

![screen shot 2018-01-03 at 15 45 33](https://user-images.githubusercontent.com/11418363/34512396-318e8368-f09d-11e7-818d-e6bf586bf93d.png)

help me, how to fix it ?

**Comment by sanghee-yoon** [comment]
Hi, @iHTCboy .
I am sorry for the late reply.

If your project supporting Korean-Only Communities, set URL Scheme value that you entered when you register your application to user NAVER Login. 

If not,(supports multiple languages except for Korean) 
1. Remove following Initialization for Korean community. 
	[[NCSDKManager getSharedInstance] setNaverLoginClientId:@"197CymaStozo7X5r2qR5"
                                     naverLoginClientSecret:@"evCgKH1kJL"
                                                     cafeId:28290504];

1. Add following Initialization for global community. 
    [[NCSDKManager getSharedInstance] setNeoIdConsumerKey:@"IHCd_HmSiMcXOMC37xZ8"
                                             communityId:1013329];

Here a guide for Initialize PLUG SDK.
[https://plug.gitbooks.io/plug-sdk-ios/content/en/[EN]-Samples.html](https://plug.gitbooks.io/plug-sdk-ios/content/en/[EN]-Samples.html)

**Comment by iHTCboy** [comment]
@sanghee-yoon  OK, Thank you! x-x~
