### ISSUE TITLE
help me!!!

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#11]
upload ipa in AppStore , recevier error message:

```
Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Specifically, we found the following unsupported architectures in your binary:

x86_64
i386

...
...

Invalid Segment Alignment - The app binary at 'myfc.app/Frameworks/KaleidoCore.framework/KaleidoCore' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

....
```

how can to do ?

**Comment by sanghee-yoon** [comment]
Hello, @iHTCboy 

1. Please check the following requirements.
* Applications: iOS 8.0 or later (64-bit architecture and bitcode supported)
* Video recording: iOS 9.0 or later, A7 or later
* IDE: XCode 7.0 or later

2. Remove unsupported architectures from KaleidoCore.framework.
lipo -remove i386 KaleidoCore -o KaleidoCore
lipo -remove x86_64 KaleidoCore -o KaleidoCore

Thanks.

**Comment by iHTCboy** [comment]
Thanks，I find dos Remove unsupported architectures from KaleidoCore.framework.

kr docs show, but english docs no't show that.... 

CHANGELOG.md:
![2018-01-12 14 16 07](https://user-images.githubusercontent.com/11418363/34862368-111dff8c-f7a5-11e7-9140-25a4680199a3.png)


README-en.md:
![2018-01-12 14 29 34](https://user-images.githubusercontent.com/11418363/34862386-2233ae52-f7a5-11e7-9f1d-e181aeede2f1.png)



docs is double like -x-
