### ISSUE TITLE
can't open url

### ISSUE THREAD

**Issue by 627969687** [naver/cafe-sdk-ios#13]
I account the 'https://plug.gitbooks.io/plug-sdk-ios/content/zh/[ZH]-%E6%A0%B7%E5%93%81.html' document to access .

**Comment by 627969687** [comment]
always crash in the open url

**Comment by 627969687** [comment]
![6bngg0bocd 0x w_p6t9s f](https://user-images.githubusercontent.com/20868764/40461273-20c56a88-5f3d-11e8-92a7-deebcb8b94e8.jpg)

**Comment by g8tauk** [comment]
@627969687 
Can I get SDK version and setup code?

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
