### ISSUE TITLE
NaverCafeSDKLive.framework 

### ISSUE THREAD

**Issue by Joicker** [naver/cafe-sdk-ios#14]
NaverCafeSDKLive.framework has no header folder,the xcode couldn't find the header file

**Comment by Joicker** [comment]
![image](https://user-images.githubusercontent.com/34057074/42920712-b56fb6aa-8b4a-11e8-8ff8-721b9d7e2895.png) where the header folder

**Comment by chenxi141017** [comment]
me too, demo can't run

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
