### ISSUE TITLE
Demo can't run

### ISSUE THREAD

**Issue by location123** [naver/cafe-sdk-ios#18]
I download your SDK from official website ，but can't run. Building error as follow
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_KFAuthentication", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
  "_OBJC_CLASS_$_KFConfig", referenced from:

I hope to solve this problem soon

**Comment by iHTCboy** [comment]
I also encountered the same problem, seeking technical classmates to solve! Online etc.!

**Comment by Hashub** [comment]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NCSDKLoginManager", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_NCSDKManager", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
