### ISSUE TITLE
URL Schemes bugs?

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#19]
if setting schemes：
![image](https://user-images.githubusercontent.com/11418363/47839690-8f3e9b80-ddee-11e8-9151-7abea1914eee.png)

login error:
![image](https://user-images.githubusercontent.com/11418363/47839768-e0e72600-ddee-11e8-9bf3-8e52e12c07aa.png)

if setting like is ok:

![image](https://user-images.githubusercontent.com/11418363/47839793-fb210400-ddee-11e8-9a02-c58cf273889b.png)

or

![image](https://user-images.githubusercontent.com/11418363/47839809-0b38e380-ddef-11e8-807e-6c4b8f420a6d.png)

The change to this configuration is not flexible, resulting in our long review and hope that you will be compatible later~ thank you!

**Comment by iHTCboy** [comment]
![image](https://user-images.githubusercontent.com/11418363/47913798-55e25a80-ded8-11e8-95cf-bf437374bbdc.png)

can't find “Headers” origin.

**Comment by iHTCboy** [comment]
in version 4.4.1  it comes again! -.-

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
