### ISSUE TITLE
When I choose the forum interface to be posted crash

### ISSUE THREAD

**Issue by qibinWang** [naver/cafe-sdk-ios#25]
When I choose the forum interface to be posted, if my account does not join the forum, I am prompted to register the cafe, click to confirm and then collapse

crash code:
-[PLGMainTabBar setSelectedIndex:] + 308
-[PLGMainView setTabBarSelectedIndex:] + 68
-[GLArticlePostViewController alertView:clickedButtonAtIndex:] + 700

Test SDK Version (4.2.1  4.2.2）

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
