### ISSUE TITLE
v.4.3.0 error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by JamesDBen** [naver/cafe-sdk-ios#26]
lipo -info /Users/xxxxx/Downloads/cafe-sdk-ios-4.3.0/lib/NaverCafeSDK.framework/NaverCafeSDK 
fatal error: /Applications/Xcode9.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /Users/coke/Downloads/cafe-sdk-ios-4.3.0/lib/NaverCafeSDK.framework/NaverCafeSDK

This version of the .framework binary is invalid.

**Comment by wen-howe** [comment]
https://github.com/naver/cafe-sdk-ios/releases

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
