### ISSUE TITLE
v.4.4.7 symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by alanxs** [naver/cafe-sdk-ios#27]
build navercafesdk-sample-ios , error
both  xcode12+ and xcode 11.5     
device: iOS14+
```
d: warning: ignoring file /Users/alan/Downloads/cafe-sdk-ios-master/lib/NaverCafeSDK.framework/NaverCafeSDK, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NCSDKLoginManager", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_NCSDKManager", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

also, can't find architecture by lipo!

```
lipo -info /Users/alan/Downloads/cafe-sdk-ios-master/lib/NaverCafeSDK.framework/NaverCafeSDK
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /Users/alan/Downloads/cafe-sdk-ios-master/lib/NaverCafeSDK.framework/NaverCafeSDK
```

**Comment by AlanCBaek** [comment]
If you download the project as a zip file, this issue occurs.
But if you clone (or check out) this project, you cannot find such issue at all.
This is so weird.

**Comment by xhp281** [comment]
> If you download the project as a zip file, this issue occurs.
> But if you clone (or check out) this project, you cannot find such issue at all.
> This is so weird.

clone doesn't work either

**Comment by wanghao615** [comment]
无论克隆还是下载ZIP都是找不到适用于架构arm64  你们解决了么

**Comment by xhp281** [comment]
the framework size is wrong

**Comment by alanxs** [comment]
I run successfully now.
the git repository used Git LFS, before you clone , you should run "git lfs install"

**Comment by AlanCBaek** [comment]
This issue is resolved by setting the option for the git lfs feature.
