### ISSUE TITLE
NaverCafeSDK.bundle

### ISSUE THREAD

**Issue by liudesu** [naver/cafe-sdk-ios#3]
![image](https://cloud.githubusercontent.com/assets/6194229/16003524/985c0b34-318f-11e6-9f45-d8b477239dd2.png)
This key will cause Error ITMS-90542 when uploading the app to iTunes store.

**Comment by conquests** [comment]
hello liudesu,
We have fixed this issue in 1.7.0 version
Thanks for your report.
