### ISSUE TITLE
theme forward color not's green ?

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#4]
run demo show low blue ?

**Comment by iHTCboy** [comment]
![screen shot 2017-04-06 at 19 17 39](https://cloud.githubusercontent.com/assets/11418363/24754742/43d56c62-1b0a-11e7-9458-54066043409e.png)

**Comment by conquests** [comment]
if you want to change theme color. refer to the APIs below

`- (void)setThemeColor:(NSString *)themeColorCSSString;`
`- (void)setThemeColor:(NSString *)themeColorCSSString andTabBackgroundColor:(NSString *)backgroundCSSString;`

**Comment by iHTCboy** [comment]
@conquests 

OK!

NCSDKColor.h
```
typedef NS_ENUM(NSUInteger, GLColorDefine) {
....
    kGLColorGreen1 = 0x00c73c,//default theme forward color
....
};
```

why the  GLColorDefine type is NSUInteger, not NSString for setThemeColor:  -.-.

**Comment by conquests** [comment]
@iHTCboy 
you will be able to use like this code
'[[NCSDKManager getSharedInstance] setThemeColor:@"#00c73c"];'

**Comment by iHTCboy** [comment]
Thank You vary much! good Job!
