### ISSUE TITLE
How can get SDK version ？

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#5]
I can't see API get version by SDK！ please, next version add Version API ？

ps: Because we encapsulated the cafe SDK and offered it to someone else, we couldn't confirm whether anyone had used the latest version.

**Comment by conquests** [comment]
you can see sdk version on screen in next version.  nonetheless, do you need API?

**Comment by iHTCboy** [comment]
@conquests  OK，we just need App launch can show sdk version in system log.  no't API, add like:

` #define KAKAO_SDK_IOS_VERSION_STRING @"1.0.47" ` OK?
