### ISSUE TITLE
iPhone X show cafe big view

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#6]
I run app in iPhone X in simulator, see :

![iPhone X show Cafe](https://user-images.githubusercontent.com/11418363/32158635-af7a8cdc-bd84-11e7-998a-bdb9603ff1bb.png)

I don't know if it's the same with real iPhoneX，if true i hope next version fix bug?

**Comment by conquests** [comment]
It will be fixed in next version.
