### ISSUE TITLE
can't run the v2.5.5 SDK in Xcode8.

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#8]
The Cafe v2.5.5 SDK uses Xcode9 and iOS11 features, resulting in compiler errors in Xcode8.

hoping to solve it? ^.^

**Comment by conquests** [comment]
In response to iPhone X and XCode 9 we made a 2.5.5.
you can use 2.5.2. if you want to work in XCode 8.

**Comment by iHTCboy** [comment]
oh!
