### ISSUE TITLE
Translate the document into English ?

### ISSUE THREAD

**Issue by happyjiahan** [naver/cafe-sdk-ios#9]
Hi there, We are using your Cafe SDK, the big problem is the document and the comments in code are not in English. So Can you translate them into English ? I think most people can read english, but only some people can read Korean。

Thanks very much!

**Comment by conquests** [comment]
Hi @happyjiahan ,

We already have a Document in English.

git > Readme-en > Documentation
https://github.com/naver/cafe-sdk-ios/blob/master/README-en.md

gitbook
https://www.gitbook.com/book/plug/plug-sdk-ios/details
https://plug.gitbooks.io/plug-sdk-ios/content/en/

Thanks
